name: Weekly Lab Update

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-labs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      issues: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: PAT access check
        run: |
          git ls-remote https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Krekensis/pps_lab_sem1_2024.git


      - name: Configure GitHub auth for private repos
        run: |
          git config --global \
            url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf \
            "https://github.com/"

      - name: Make lab_manage.sh executable
        run: chmod +x ./lab_manage.sh

      - name: Prepare working tree
        run: |
          git reset --hard
          git clean -fd

      - name: Update PPS
        run: bash ./lab_manage.sh update https://github.com/Krekensis/pps_lab_sem1_2024.git "Semester 1" PPS main

      - name: Update DV
        run: bash ./lab_manage.sh update https://github.com/Krekensis/dv_lab_sem2_2025.git "Semester 2" DV main

      - name: Update OOP
        run: bash ./lab_manage.sh update https://github.com/Krekensis/oop_lab_sem2_2025.git "Semester 2" OOP main

      - name: Update DS
        run: bash ./lab_manage.sh update https://github.com/Krekensis/ds_lab_sem3_2025.git "Semester 3" DS main

      - name: Update OOSD
        run: bash ./lab_manage.sh update https://github.com/Krekensis/oosd_lab_sem4_2026.git "Semester 4" OOSD main
        
      - name: Push updates
        run: |
          git fetch origin main

          if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
            echo "New commits detected â€” pushing to GitHub"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          else
            echo "No new commits to push"
          fi